/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApiKeyStatus {
  'did' : boolean,
  'openai' : boolean,
  'elevenlabs' : boolean,
}
export interface JobRecord {
  'id' : string,
  'status' : string,
  'createdAt' : bigint,
  'errorMessage' : [] | [string],
  'audioUrl' : [] | [string],
  'scriptResult' : [] | [ScriptResult],
  'videoUrl' : [] | [string],
}
export interface ScriptResult {
  'fullScript' : string,
  'hook' : string,
  'callToAction' : string,
  'solution' : string,
  'estimatedDuration' : bigint,
  'problem' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'generateScript' : ActorMethod<[string, string, string], string>,
  'generateVoiceover' : ActorMethod<[string, string], string>,
  'getApiKeyStatus' : ActorMethod<[], ApiKeyStatus>,
  'getJob' : ActorMethod<[string], [] | [JobRecord]>,
  'getVideoStatus' : ActorMethod<[string], string>,
  'listJobs' : ActorMethod<[], Array<JobRecord>>,
  'setApiKeys' : ActorMethod<[string, string, string], undefined>,
  'startVideoGeneration' : ActorMethod<[string, string], string>,
  'transformRelay' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];