/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ApiKeyStatus = IDL.Record({
  'did' : IDL.Bool,
  'openai' : IDL.Bool,
  'elevenlabs' : IDL.Bool,
});
export const ScriptResult = IDL.Record({
  'fullScript' : IDL.Text,
  'hook' : IDL.Text,
  'callToAction' : IDL.Text,
  'solution' : IDL.Text,
  'estimatedDuration' : IDL.Nat,
  'problem' : IDL.Text,
});
export const JobRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'errorMessage' : IDL.Opt(IDL.Text),
  'audioUrl' : IDL.Opt(IDL.Text),
  'scriptResult' : IDL.Opt(ScriptResult),
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'generateScript' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'generateVoiceover' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getApiKeyStatus' : IDL.Func([], [ApiKeyStatus], ['query']),
  'getJob' : IDL.Func([IDL.Text], [IDL.Opt(JobRecord)], ['query']),
  'getVideoStatus' : IDL.Func([IDL.Text], [IDL.Text], []),
  'listJobs' : IDL.Func([], [IDL.Vec(JobRecord)], ['query']),
  'setApiKeys' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'startVideoGeneration' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'transformRelay' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ApiKeyStatus = IDL.Record({
    'did' : IDL.Bool,
    'openai' : IDL.Bool,
    'elevenlabs' : IDL.Bool,
  });
  const ScriptResult = IDL.Record({
    'fullScript' : IDL.Text,
    'hook' : IDL.Text,
    'callToAction' : IDL.Text,
    'solution' : IDL.Text,
    'estimatedDuration' : IDL.Nat,
    'problem' : IDL.Text,
  });
  const JobRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'errorMessage' : IDL.Opt(IDL.Text),
    'audioUrl' : IDL.Opt(IDL.Text),
    'scriptResult' : IDL.Opt(ScriptResult),
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'generateScript' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'generateVoiceover' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getApiKeyStatus' : IDL.Func([], [ApiKeyStatus], ['query']),
    'getJob' : IDL.Func([IDL.Text], [IDL.Opt(JobRecord)], ['query']),
    'getVideoStatus' : IDL.Func([IDL.Text], [IDL.Text], []),
    'listJobs' : IDL.Func([], [IDL.Vec(JobRecord)], ['query']),
    'setApiKeys' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'startVideoGeneration' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'transformRelay' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };